spring:
  application:
    name: dockerized.postgresql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: root
   password: root

server:
  port: 8093
